# Testes usecases

### Teste de criação de documento

Primeiramente vamos ajustar o nosso arquivo `test_product.py`para o código abaixo:

```python
from store.usecases.product import product_usecases

async def test_usecases_should_return_sucess(product_in):
    result = await product_usecases.create(body=product_in)

    assert isinstance(result, ProductOut)
```

Se tentarmos rodar o `make test` teremos um erro, afinal, ainda não temos a definição de `ProductOut`. Vamos corrigir isso. No diretório `store/schemas` abra o arquivo `product.py`. Vamos criar a classe `ProductOut`:

```python
from pydantic import Field
from store.schemas.base import BaseSchemaMixin

class ProductIn(BaseSchemaMixin):
    name: str = Field(..., description="Product name")
    quantity: int = Field(..., description="Product quantity")
    price: float = Field(..., description="Product price")
    status: bool = Field(..., description="Product status")

class ProductOut(ProductIn):
    ...

```

Agora no diretório `store/usecases` abra o arquivo `product.py` e atualize o código para:

```python
from motor.motor_asyncio import AsyncIOMotorClient, AsyncIOMotorDatabase
from store.db.mongo import db_client
from store.schemas.product import ProductIn, ProductOut

class ProductUsecase:
    def __init__(self) -> None:
        self.client: AsyncIOMotorClient = db_client.get()
        self.database: AsyncIOMotorDatabase = self.client.get_database()
        self.collection = self.database.get_collection("products")

    async def create(self, body: ProductIn) -> ProductOut:
        product = ProductOut(**body.model_dump())
        await self.collection.insert_one(product.model_dump())

        return product

product_usecases = ProductUsecase()
```

Também atualize a importação do arquivo `test_product.py`:

```python
from store.schemas.product import ProductOut
from store.usecases.product import product_usecases

async def test_usecases_should_return_sucess(product_in):
    result = await product_usecases.create(body=product_in)

    assert isinstance(result, ProductOut)
    assert result.name == "Iphone 14 pro Max"
```

Feito isso, teste a aplicação com `make test`. Se tudo estiver correto, deverá passar sem problemas.

![Untitled](/docs/img/05_img/Untitled.png)

### Teste de busca por ID

Vamos adicionar mais um teste ao `test_product.py`. Adicione a função abaixo no final do arquivo:

```python
async def test_usecases_get_should_return_sucess(product_id):
    result = await product_usecases.get(id=product_id)

    assert isinstance(result, ProductOut)
    assert result.name == "Iphone 14 pro Max"
```

Se testarmos agora, deverá voltar um erro, afinal ainda não definimos a função `get`. Vamos corrigir isso. Em `store/usecases` abra o arquivo `product.py` e atualize o código para:

```python
from uuid import UUID
from motor.motor_asyncio import AsyncIOMotorClient, AsyncIOMotorDatabase
from store.db.mongo import db_client
from store.schemas.product import ProductIn, ProductOut

class ProductUsecase:
    def __init__(self) -> None:
        self.client: AsyncIOMotorClient = db_client.get()
        self.database: AsyncIOMotorDatabase = self.client.get_database()
        self.collection = self.database.get_collection("products")

    async def create(self, body: ProductIn) -> ProductOut:
        product = ProductOut(**body.model_dump())
        await self.collection.insert_one(product.model_dump())

        return product

    async def get(self, id: UUID) -> ProductOut:
        result = await self.collection.find_one({"id": id})

        return ProductOut(**result)

product_usecases = ProductUsecase()
```

Ao executar o `make test` deverá passar sem problemas.

![Untitled](/docs/img/05_img/Untitled1.png)

### Teste de ID não encontrado

Criaremos um cenário agora para testar quando o ID não é encontrado. Para isso, em `test_product.py` atualize o código para:

```python
from uuid import UUID

import pytest
from store.schemas.product import ProductOut
from store.usecases.product import product_usecases

async def test_usecases_should_return_sucess(product_in):
    result = await product_usecases.create(body=product_in)

    assert isinstance(result, ProductOut)
    assert result.name == "Iphone 14 pro Max"

async def test_usecases_get_should_return_sucess(product_id):
    result = await product_usecases.get(id=product_id)

    assert isinstance(result, ProductOut)
    assert result.name == "Iphone 14 pro Max"

async def test_usecases_get_should_not_found():
    with pytest.raises(Exception) as err:
        await product_usecases.get(id=UUID('1d37ae03-20ef-4124-8a73-b293960c4dde'))

    assert err.value.message == "Product not found with filter: 1d37ae03-20ef-4124-8a73-b293960c4dde"

```

Agora precisamos tratar a mensagem de erro. Em `store/usecases` abra o arquivo `product.py` e atualize o código para:

```python
from uuid import UUID
from motor.motor_asyncio import AsyncIOMotorClient, AsyncIOMotorDatabase
from store.db.mongo import db_client
from store.schemas.product import ProductIn, ProductOut

class ProductUsecase:
    def __init__(self) -> None:
        self.client: AsyncIOMotorClient = db_client.get()
        self.database: AsyncIOMotorDatabase = self.client.get_database()
        self.collection = self.database.get_collection("products")

    async def create(self, body: ProductIn) -> ProductOut:
        product = ProductOut(**body.model_dump())
        await self.collection.insert_one(product.model_dump())

        return product

    async def get(self, id: UUID) -> ProductOut:
        result = await self.collection.find_one({"id": id})

        if not result:
            raise NotFoundException(message=f"Product not found with filter: {id}")

        return ProductOut(**result)

product_usecases = ProductUsecase()
```

Para customização da mensagem, em `store/core/` crie um arquivo chamdo`exceptions.py`. Utilize este código:

```python
class BaseException(Exception):
    message: str = "Internal Server Error"

    def __init__(self, message: str | None = None) -> None:

        if message:
            self.message = message

class NotFound(BaseException):
    message = "Not Found"
```

Ao rodar o `make test` deverá passar sem problemas:

![Untitled](/docs/img/05_img/Untitled2.png)

### Teste de Query

Vamos criar agora um teste para retornar uma lista de itens. Para isso, em `test_product.py` inclua a seguinte função no final do arquivo:

```python
async def test_usecases_query_should_return_sucess():
    result = await product_usecases.query()

    assert isinstance(result, list)
```

Se tentarmos testar agora, deverá falhar pois ainda não criamos a função `query`. Antes de corrigirmos nosso código, vamos incluir uma função no `Makefile` para execução de testes específicos:

```python
run:
	@uvicorn store.main:app --reload

precommit-install:
	@poetry run pre-commit install

test:
	@poetry run pytest

test-matching:
	@poetry run pytest -s -rx -k $(K) --pdb store ./tests/
```

Para executar esta nova função, no Terminal utilizamos: `make test-matching K=nome_da_função_testada`. Neste caso, utilizaremos agora a função `test_usecases_query_should_return_sucess`, que deverá apresentar erro:

Agora, vamos corrigir a falha pela falta da função query em `store/usecases` abra o arquivo `product.py` e atualize o código para:

```python
from typing import List
from uuid import UUID
from motor.motor_asyncio import AsyncIOMotorClient, AsyncIOMotorDatabase
from store.db.mongo import db_client
from store.schemas.product import ProductIn, ProductOut
from store.core.exceptions import NotFoundException

class ProductUsecase:
    def __init__(self) -> None:
        self.client: AsyncIOMotorClient = db_client.get()
        self.database: AsyncIOMotorDatabase = self.client.get_database()
        self.collection = self.database.get_collection("products")

    async def create(self, body: ProductIn) -> ProductOut:
        product = ProductOut(**body.model_dump())
        await self.collection.insert_one(product.model_dump())

        return product

    async def get(self, id: UUID) -> ProductOut:
        result = await self.collection.find_one({"id": id})

        if not result:
            raise NotFoundException(message=f"Product not found with filter: {id}")

        return ProductOut(**result)

    async def query(self) -> List[ProductOut]:
        return [ProductOut(**item) async for item in self.collection.find()]

product_usecases = ProductUsecase()
```

Rodando novamente o `make test-matching K=test_usecases_query_should_return_sucess` deverá passar sem problemas:

![Untitled](/docs/img/05_img/Untitled3.png)

### Teste de Update

Para testarmos o update de um item, em `test_product.py` inclua a função no final do arquivo:

```python
async def test_usecases_update_should_return_sucess(product_id, product_up):
    result = await product_usecases.update(id=product_id, body=product_up)

    assert isinstance(result, ProductOut)
```

Precisamos atualizar o arquivo `store/schemas/product.py`:

```python
from typing import Optional
from pydantic import BaseModel, Field
from store.schemas.base import BaseSchemaMixin

class ProductBase(BaseModel):
    name: str = Field(..., description="Product name")
    quantity: int = Field(..., description="Product quantity")
    price: float = Field(..., description="Product price")
    status: bool = Field(..., description="Product status")

class ProductIn(ProductBase, BaseSchemaMixin):
    ...

class ProductOut(ProductIn):
    ...

class ProductUpdate(ProductBase):
    quantity: Optional[int] = Field(None, description="Product quantity")
    price: Optional[float] = Field(None, description="Product price")
    status: Optional[bool] = Field(None, description="Product status")

class ProductUpdateOut(ProductUpdate):
    ...
```

Feito isso atualizaremos também o código de `store/usecases/product.py`:

```python
from typing import List
from uuid import UUID
from motor.motor_asyncio import AsyncIOMotorClient, AsyncIOMotorDatabase
import pymongo
from store.db.mongo import db_client
from store.schemas.product import ProductIn, ProductOut, ProductUpdate, ProductUpdateOut
from store.core.exceptions import NotFoundException

class ProductUsecase:
    def __init__(self) -> None:
        self.client: AsyncIOMotorClient = db_client.get()
        self.database: AsyncIOMotorDatabase = self.client.get_database()
        self.collection = self.database.get_collection("products")

    async def create(self, body: ProductIn) -> ProductOut:
        product = ProductOut(**body.model_dump())
        await self.collection.insert_one(product.model_dump())

        return product

    async def get(self, id: UUID) -> ProductOut:
        result = await self.collection.find_one({"id": id})

        if not result:
            raise NotFoundException(message=f"Product not found with filter: {id}")

        return ProductOut(**result)

    async def query(self) -> List[ProductOut]:
        return [ProductOut(**item) async for item in self.collection.find()]

    async def update(self, id:UUID, body: ProductUpdate) -> ProductUpdateOut:
        result = await self.collection.find_one_and_update(
            filter={"id": id},
            update={"$set": body.model_dump(exclude_none=True)},
            return_document=pymongo.ReturnDocument.AFTER
        )
        return ProductUpdateOut(**result)

product_usecases = ProductUsecase()
```

Inclua também em `conftest.py` a função no final do arquivo:

```python
@pytest.fixture
def product_up(product_id):
    return ProductUpdate(**product_data(), id=product_id)
```

### Teste de Delete com sucesso

Para completar o CRUD, vamos testar também a função Delete.

>:thought_balloon: CRUD - Create, Read, Update and Delete
>Resume as quatro operações básicas para gerenciar dados em um banco de dados: **Criar, Ler, Atualizar e Excluir**. Essas ações são essenciais para interagir com dados em diversos sistemas, desde aplicações simples até softwares complexos.

Em `test_product.py` inclua a função no final do arquivo:

```python
async def test_usecases_delete_should_return_sucess(product_id):
    result = await product_usecases.delete(id=product_id)

    assert result is True
```

Ao testar com `make test` obviamente irá falhar, pois ainda não criamos a função `delete`. Vamos corrigir isso incluindo a função no final de `store/usecases/product.py`:

```python
async def delete(self, id: UUID) -> bool:
        result = await self.collection.delete_one({"id": id})
        return True if result.delete_count > 0 else False
```

O teste com `make test` agora deverá passar sem problemas:

![Untitled](/docs/img/05_img/Untitled4.png)

### Teste de Delete com falha

Inclua a função abaixo em `test_product.py`:

```python
async def test_usecases_delete_should_not_found():
    with pytest.raises(NotFoundException) as err:
        await product_usecases.delete(id=UUID('1d37ae03-20ef-4124-8a73-b293960c4dde'))

    assert err.value.message == "Product not found with filter: 1d37ae03-20ef-4124-8a73-b293960c4dde"
```

Antes de tratarmos a `raise` necessária para passar este teste, vamos voltar em `conftest.py`e reativar a função que fazia a limpeza do banco. Isso irá quebrar outros testes, porém vamos corrigir logo depois. Procure a função abaixo e atualize:

```python
@pytest.fixture(autouse=True)
async def clear_collections(mongo_client):
    yield
    collection_names = await mongo_client.get_database().list_collection_names()
    for collection_name in collection_names:
        if collection_name.startswith("system"):
            continue

        await mongo_client.get_database()[collection_name].delete_many({})
```

Rode `make test` e na sequência volte a comentar a linha abaixo:

![Untitled](/docs/img/05_img/Untitled5.png)

Em `store/usecases/product.py` vamos atualizar a função `delete`:

```python
async def delete(self, id: UUID) -> bool:
        product = await self.collection.find_one({"id": id})
        if not product:
            raise NotFoundException(message=f"Product not found with filter: {id}")

        result = await self.collection.delete_one({"id": id})

        return True if result.deleted_count > 0 else False
```

Rode `make test` novamente para confirmar a funcionalidade de nossa aplicação:

![Untitled](/docs/img/05_img/Untitled6.png)

### Corrigindo conftest.py

Haviamos deixado uma linha comentada em `conftest.py`. Essa função em questão faz a limpeza do banco a cada teste executado.

![Untitled](/docs/img/05_img/Untitled7.png)

Porém, existem funções que dependem da existência de dados no banco para serem executadas. Para corrigir isso, vamos criar uma função que cria o dado antes da execução dessas funções.

Em `conftest.py` vamos atualizar conforme abaixo:

```python
from uuid import UUID
import pytest
import asyncio

from store.db.mongo import db_client
from store.schemas.product import ProductIn, ProductUpdate
from store.usecases.product import product_usecases
from tests.schemas.factories import product_data

@pytest.fixture(scope="session")
def event_loop():
    loop = asyncio.get_event_loop_policy().new_event_loop()
    yield loop
    loop.close()

@pytest.fixture
def mongo_client():
    return db_client.get()

@pytest.fixture(autouse=True)
async def clear_collections(mongo_client):
    yield
    collection_names = await mongo_client.get_database().list_collection_names()
    for collection_name in collection_names:
        if collection_name.startswith("system"):
            continue

        await mongo_client.get_database()[collection_name].delete_many({})

@pytest.fixture
def product_id() -> UUID:
    return UUID("fce6cc37-10b9-4a8e-a8b2-977df327001a")

@pytest.fixture
def product_in(product_id):
    return ProductIn(**product_data(), id=product_id)

@pytest.fixture
def product_up(product_id):
    return ProductUpdate(**product_data(), id=product_id)

@pytest.fixture
async def product_inserted(product_in):
    return await product_usecases.create(body=product_in)
```

Agora precisamos ajustar também o arquivo `test_product.py` para utilização apropriada das funções criadas:

```python
from uuid import UUID
import pytest
from store.core.exceptions import NotFoundException
from store.schemas.product import ProductOut, ProductUpdateOut
from store.usecases.product import product_usecases

async def test_usecases_should_return_sucess(product_in):
    result = await product_usecases.create(body=product_in)

    assert isinstance(result, ProductOut)
    assert result.name == "Iphone 14 pro Max"

async def test_usecases_get_should_return_success(product_inserted):
    result = await product_usecases.get(id=product_inserted.id)

    assert isinstance(result, ProductOut)
    assert result.name == "Iphone 14 pro Max"

async def test_usecases_get_should_not_found():
    with pytest.raises(NotFoundException) as err:
        await product_usecases.get(id=UUID('1d37ae03-20ef-4124-8a73-b293960c4dde'))

    assert err.value.message == "Product not found with filter: 1d37ae03-20ef-4124-8a73-b293960c4dde"

async def test_usecases_query_should_return_sucess():
    result = await product_usecases.query()

    assert isinstance(result, list)

async def test_usecases_update_should_return_sucess(product_up, product_inserted):
    product_up.price = 7.500
    result = await product_usecases.update(id=product_inserted.id, body=product_up)

    assert isinstance(result, ProductUpdateOut)

async def test_usecases_delete_should_return_sucess(product_inserted):
    result = await product_usecases.delete(id=product_inserted.id)

    assert result is True

async def test_usecases_delete_should_not_found():
    with pytest.raises(NotFoundException) as err:
        await product_usecases.delete(id=UUID('1d37ae03-20ef-4124-8a73-b293960c4dde'))

    assert err.value.message == "Product not found with filter: 1d37ae03-20ef-4124-8a73-b293960c4dde"
```

Ao executar o `make test` os 9 testes deverão passar sem erro:

![Untitled](/docs/img/05_img/Untitled8.png)

### Corrigindo a função Query

No estado atual do nosso projeto, ao executarmos a função query, o retorno será sempre uma lista vazia. Isso acontece pois nosso código limpa o banco toda vez que é executado o `make test`. Vamos ajustar nosso código para corrigir este problema. Primeiramente, vamos criar mais um produto *mock.* Em `tests/schemas/factories.py` atualize conforme abaixo:

```python
def product_data():
    return {
        "name": "Iphone 14 pro Max",
        "quantity": 10,
        "price": 8.500,
        "status": True
    }

def product_broken_data():
    return {'name': 'Iphone 14 pro Max', 'quantity': 10, 'price': 8.500}

def products_data():
    return [
        {"name": "Iphone 11 Pro Max",
         "quantity": 20,
         "price": "4.500",
         "status": True
        },
        {"name": "Iphone 12 Pro Max",
         "quantity": 15, "price": "5.500",
         "status": True},
        {"name": "Iphone 13 Pro Max",
         "quantity": 5,
         "price": "6.500",
         "status": True
        },
        {"name": "Iphone 15 Pro Max",
         "quantity": 3,
         "price": "10.500",
         "status": False,
        },
    ]
```

Feito isso, vamos atualizar também `conftest.py`:

```python
from uuid import UUID
import pytest
import asyncio

from store.db.mongo import db_client
from store.schemas.product import ProductIn, ProductUpdate
from store.usecases.product import product_usecases
from tests.schemas.factories import product_data, products_data

@pytest.fixture(scope="session")
def event_loop():
    loop = asyncio.get_event_loop_policy().new_event_loop()
    yield loop
    loop.close()

@pytest.fixture
def mongo_client():
    return db_client.get()

@pytest.fixture(autouse=True)
async def clear_collections(mongo_client):
    yield
    collection_names = await mongo_client.get_database().list_collection_names()
    for collection_name in collection_names:
        if collection_name.startswith("system"):
            continue

        await mongo_client.get_database()[collection_name].delete_many({})

@pytest.fixture
def product_id() -> UUID:
    return UUID("fce6cc37-10b9-4a8e-a8b2-977df327001a")

@pytest.fixture
def product_in(product_id):
    return ProductIn(**product_data(), id=product_id)

@pytest.fixture
def product_up(product_id):
    return ProductUpdate(**product_data(), id=product_id)

@pytest.fixture
async def product_inserted(product_in):
    return await product_usecases.create(body=product_in)

@pytest.fixture
def products_in(product_id):
    return [ProductIn(**product_data(), id=product_id) for product in products_data()]

@pytest.fixture
async def products_inserted(products_in):
    return [await product_usecases.create(body=product_in) for product_in in products_in]

```

Agora vamos atualizar nosso `test_product.py`:

```python
from uuid import UUID
import pytest
from store.core.exceptions import NotFoundException
from store.schemas.product import ProductOut, ProductUpdateOut
from store.usecases.product import product_usecases

async def test_usecases_should_return_sucess(product_in):
    result = await product_usecases.create(body=product_in)

    assert isinstance(result, ProductOut)
    assert result.name == "Iphone 14 pro Max"

async def test_usecases_get_should_return_success(product_inserted):
    result = await product_usecases.get(id=product_inserted.id)

    assert isinstance(result, ProductOut)
    assert result.name == "Iphone 14 pro Max"

async def test_usecases_get_should_not_found():
    with pytest.raises(NotFoundException) as err:
        await product_usecases.get(id=UUID('1d37ae03-20ef-4124-8a73-b293960c4dde'))

    assert err.value.message == "Product not found with filter: 1d37ae03-20ef-4124-8a73-b293960c4dde"

@pytest.mark.usefixtures("products_inserted")
async def test_usecases_query_should_return_sucess():
    result = await product_usecases.query()

    assert isinstance(result, list)
    assert len(result) > 1

async def test_usecases_update_should_return_sucess(product_up, product_inserted):
    product_up.price = 7.500
    result = await product_usecases.update(id=product_inserted.id, body=product_up)

    assert isinstance(result, ProductUpdateOut)

async def test_usecases_delete_should_return_sucess(product_inserted):
    result = await product_usecases.delete(id=product_inserted.id)

    assert result is True

async def test_usecases_delete_should_not_found():
    with pytest.raises(NotFoundException) as err:
        await product_usecases.delete(id=UUID('1d37ae03-20ef-4124-8a73-b293960c4dde'))

    assert err.value.message == "Product not found with filter: 1d37ae03-20ef-4124-8a73-b293960c4dde"

```

Ao executar o `make test` o código deverá rodar sem problemas:

![Untitled](/docs/img/05_img/Untitled9.png)

Com isso podemos seguir nosso projeto para corrigir e trabalhar na [Criação de Models](/docs/content/06.md)
